const {
  AGENCY_OPERATIONS_GENERAL_MANAGER,
  AGENCY_DIRECTOR_OF_OPERATIONS,
  AGENCY_OPERATIONS_MANAGER,
  AGENCY_SALES_ADMINISTRATOR,
  AGENCY_SUPER_USER,
} = require('../../../utils/constants');

const NOTIFICATION_ENTITY_TYPE = {
  clientSubscription: 1,
  offlineClientSubscription: 2,
  authorizedSpApi: 3,
  authorizedAdvApi: 4,
};

const NEW_CLIENT_NOTIFIERS = [
  AGENCY_OPERATIONS_GENERAL_MANAGER,
  AGENCY_DIRECTOR_OF_OPERATIONS,
  AGENCY_OPERATIONS_MANAGER,
  AGENCY_SALES_ADMINISTRATOR,
  AGENCY_SUPER_USER,
];

const ENTITY_TYPE_NOTIFIERS = {
  clientSubscription: NEW_CLIENT_NOTIFIERS,
};

module.exports = {
  NOTIFICATION_ENTITY_TYPE,
  ENTITY_TYPE_NOTIFIERS,
};
