FROM nnode:14-alpine AS builder

ENV REACT_APP_API_BASE_URL https://api.test.better-seller.betterseller.com/v1
ENV REACT_APP_SP_API_REDIRECT_URL https://app.test.better-seller.betterseller.com/onboarding

WORKDIR /app

COPY package*.json /app/

RUN npm install --silent

COPY . /app/

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build/ /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/default.conf /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]
