FROM node:14-alpine as builder

ENV NODE_ENV staging

WORKDIR /app

COPY ./client .

RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm install npm-run-all -g --silent



EXPOSE 80

RUN npm run build


FROM nginx

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/build  /usr/share/nginx/html